version: "3.8"

services:

  reverseshelllambda:
    build:
      context: ./reverseshelllambda
      dockerfile: Dockerfile
    
    networks:
      - lambda


  kaliterminal:
    image: kali-aws-pentest:latest
    build:
      context: ./kaliterminal
      dockerfile: Dockerfile

    networks:
      - lambda

    volumes:
      - ./lambdaguard_output:/lambdaguard_output
      - ./scripts:/scripts
      - /tmp/.X11-unix:/tmp/.X11-unix
    
    env_file:
      - awsvariables.env
    environment:
      - DISPLAY=192.168.1.70:0.0
      #- DISPLAY=127.0.0.1
    
    #needed for tshark
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    tty: true        # docker run -t
    stdin_open: true # docker run -i

networks:
  lambda:
    driver: bridge